# Generated by Django 6.0.4 on 2026-06-28 04:14

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
