# Generated by Django 6.0.4 on 2026-06-28 04:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True),
        ),
    ]
